# Docker compose file for the MYSQL server
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-8.0
    restart: unless-stopped                       # always restart
    environment:
      MYSQL_DATABASE: 'wa-project'              # name of database
      MYSQL_USER: 'server'                # sample is the name of user
      MYSQL_PASSWORD: 'password'          # password for sample user
      MYSQL_ROOT_PASSWORD: 'password'     # password for root user
    ports:
      - '3306:3306'                       # host port 3306 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # copy init.sql to docker entry point
volumes:
  mysql-db: