package com.f1setups.models;

import java.time.LocalDateTime;
import java.util.Date;

/*
    * This class represents a Setup in the system. It contains both the metadata
    * and the actual telemetry of the setup.
    * the id is auto-generated by MySQL
 */
public class Setup
{
    // Metadata fields
    private int id;
    private int userId; // the id of the user who created the setup
    private int gameVersionId; // id of the game versions catalog
    private int trackId; // id of the track catalog
    private int teamId; // id of the team catalog
    private String title; // tile for the record
    private String annotation; // user's annotations for the record
    private SessionType sessionType; // value of the enum
    private ControllerType controllerType;  // value of the enum
    private Boolean isWetWeather; // if the record is marked for wet weather
    private LocalDateTime createdAt; // date of creation of the record
    // Setup fields
    // Aero
    private int frontWing;
    private int rearWing;
    // Transmission
    private int diffOnThrottle;
    private int diffOffThrottle;
    private int engineBraking;
    // Suspension geometry
    private float frontCamber;
    private float rearCamber;
    private float frontToe;
    private float rearToe;
    // Suspension
    private int frontSuspension;
    private int rearSuspension;
    private int frontAntiRollBar;
    private int rearAntiRollBar;
    private int frontRideHeight;
    private int rearRideHeight;
    // Brakes
    private int brakePressure;
    private int brakeBias;
    // Tyres
    private float frontRightPressure;
    private float frontLeftPressure;
    private float rearRightPressure;
    private float rearLeftPressure;

    public Setup(int id, int userId, int gameVersionId, int trackId, int teamId, String title, String annotation, SessionType sessionType, ControllerType controllerType, Boolean isWetWeather, LocalDateTime createdAt, int frontWing, int rearWing, int diffOnThrottle, int diffOffThrottle, int engineBraking, float frontCamber, float rearCamber, float frontToe, float rearToe, int frontSuspension, int rearSuspension, int frontAntiRollBar, int rearAntiRollBar, int frontRideHeight, int rearRideHeight, int brakePressure, int brakeBias, float frontRightPressure, float frontLeftPressure, float rearRightPressure, float rearLeftPressure) {
        this.id = id;
        this.userId = userId;
        this.gameVersionId = gameVersionId;
        this.trackId = trackId;
        this.teamId = teamId;
        this.title = title;
        this.annotation = annotation;
        this.sessionType = sessionType;
        this.controllerType = controllerType;
        this.isWetWeather = isWetWeather;
        this.createdAt = createdAt;
        this.frontWing = frontWing;
        this.rearWing = rearWing;
        this.diffOnThrottle = diffOnThrottle;
        this.diffOffThrottle = diffOffThrottle;
        this.engineBraking = engineBraking;
        this.frontCamber = frontCamber;
        this.rearCamber = rearCamber;
        this.frontToe = frontToe;
        this.rearToe = rearToe;
        this.frontSuspension = frontSuspension;
        this.rearSuspension = rearSuspension;
        this.frontAntiRollBar = frontAntiRollBar;
        this.rearAntiRollBar = rearAntiRollBar;
        this.frontRideHeight = frontRideHeight;
        this.rearRideHeight = rearRideHeight;
        this.brakePressure = brakePressure;
        this.brakeBias = brakeBias;
        this.frontRightPressure = frontRightPressure;
        this.frontLeftPressure = frontLeftPressure;
        this.rearRightPressure = rearRightPressure;
        this.rearLeftPressure = rearLeftPressure;
    }

    public int getId() {
        return id;
    }

    public int getUserId() {
        return userId;
    }

    public int getGameVersionId() {
        return gameVersionId;
    }

    public int getTrackId() {
        return trackId;
    }

    public int getTeamId() {
        return teamId;
    }

    public String getTitle() {
        return title;
    }

    public String getAnnotation() {
        return annotation;
    }

    public SessionType getSessionType() {
        return sessionType;
    }

    public ControllerType getControllerType() {
        return controllerType;
    }

    public Boolean getWetWeather() {
        return isWetWeather;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public int getFrontWing() {
        return frontWing;
    }

    public int getRearWing() {
        return rearWing;
    }

    public int getDiffOnThrottle() {
        return diffOnThrottle;
    }

    public int getDiffOffThrottle() {
        return diffOffThrottle;
    }

    public int getEngineBraking() {
        return engineBraking;
    }

    public float getFrontCamber() {
        return frontCamber;
    }

    public float getRearCamber() {
        return rearCamber;
    }

    public float getFrontToe() {
        return frontToe;
    }

    public float getRearToe() {
        return rearToe;
    }

    public int getFrontSuspension() {
        return frontSuspension;
    }

    public int getRearSuspension() {
        return rearSuspension;
    }

    public int getFrontAntiRollBar() {
        return frontAntiRollBar;
    }

    public int getRearAntiRollBar() {
        return rearAntiRollBar;
    }

    public int getFrontRideHeight() {
        return frontRideHeight;
    }

    public int getRearRideHeight() {
        return rearRideHeight;
    }

    public int getBrakePressure() {
        return brakePressure;
    }

    public int getBrakeBias() {
        return brakeBias;
    }

    public float getFrontRightPressure() {
        return frontRightPressure;
    }

    public float getFrontLeftPressure() {
        return frontLeftPressure;
    }

    public float getRearRightPressure() {
        return rearRightPressure;
    }

    public float getRearLeftPressure() {
        return rearLeftPressure;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public void setGameVersionId(int gameVersionId) {
        this.gameVersionId = gameVersionId;
    }

    public void setTrackId(int trackId) {
        this.trackId = trackId;
    }

    public void setTeamId(int teamId) {
        this.teamId = teamId;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setAnnotation(String annotation) {
        this.annotation = annotation;
    }

    public void setSessionType(SessionType sessionType) {
        this.sessionType = sessionType;
    }

    public void setControllerType(ControllerType controllerType) {
        this.controllerType = controllerType;
    }

    public void setWetWeather(Boolean wetWeather) {
        isWetWeather = wetWeather;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setFrontWing(int frontWing) {
        this.frontWing = frontWing;
    }

    public void setRearWing(int rearWing) {
        this.rearWing = rearWing;
    }

    public void setDiffOnThrottle(int diffOnThrottle) {
        this.diffOnThrottle = diffOnThrottle;
    }

    public void setDiffOffThrottle(int diffOffThrottle) {
        this.diffOffThrottle = diffOffThrottle;
    }

    public void setEngineBraking(int engineBraking) {
        this.engineBraking = engineBraking;
    }

    public void setFrontCamber(float frontCamber) {
        this.frontCamber = frontCamber;
    }

    public void setRearCamber(float rearCamber) {
        this.rearCamber = rearCamber;
    }

    public void setFrontToe(float frontToe) {
        this.frontToe = frontToe;
    }

    public void setRearToe(float rearToe) {
        this.rearToe = rearToe;
    }

    public void setFrontSuspension(int frontSuspension) {
        this.frontSuspension = frontSuspension;
    }

    public void setRearSuspension(int rearSuspension) {
        this.rearSuspension = rearSuspension;
    }

    public void setFrontAntiRollBar(int frontAntiRollBar) {
        this.frontAntiRollBar = frontAntiRollBar;
    }

    public void setRearAntiRollBar(int rearAntiRollBar) {
        this.rearAntiRollBar = rearAntiRollBar;
    }

    public void setFrontRideHeight(int frontRideHeight) {
        this.frontRideHeight = frontRideHeight;
    }

    public void setRearRideHeight(int rearRideHeight) {
        this.rearRideHeight = rearRideHeight;
    }

    public void setBrakePressure(int brakePressure) {
        this.brakePressure = brakePressure;
    }

    public void setBrakeBias(int brakeBias) {
        this.brakeBias = brakeBias;
    }

    public void setFrontRightPressure(float frontRightPressure) {
        this.frontRightPressure = frontRightPressure;
    }

    public void setFrontLeftPressure(float frontLeftPressure) {
        this.frontLeftPressure = frontLeftPressure;
    }

    public void setRearRightPressure(float rearRightPressure) {
        this.rearRightPressure = rearRightPressure;
    }

    public void setRearLeftPressure(float rearLeftPressure) {
        this.rearLeftPressure = rearLeftPressure;
    }

    @Override
    public String toString()
    {
        return "";
    }
}
