package com.f1setups.models;

/*
    * This class represents a user in the system. It contains the user's id, username, password and email.
    * The password is hashed using BCrypt and salted with a random salt generated for each user.
    * the id is auto-generated by MySQL
 */
public class User
{
    private final int id;
    private final String username;
    private final String email;
    private final String password;
    private final String salt;

    public User(int id, String username, String email, String password, String salt)
    {
        this.id = id;
        this.username = username;
        this.email = email;
        this.password = password;
        this.salt = salt;
    }

    public int getId()
    {
        return id;
    }
    public String getUsername()
    {
        return username;
    }
    public String getEmail()
    {
        return email;
    }

    public String getPassword()
    {
        return password;
    }
    public String getSalt()
    {
        return salt;
    }

    @Override
    public String toString()
    {
        return "id" + id + "name: " + username + " email: " + email;
    }
}